/*
FORCESPRONLPsolver : A fast customized optimization solver.

Copyright (C) 2013-2023 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.3.0 on Saturday, May 4, 2024 at 8:12:11 AM */
#ifndef FORCESPRONLPsolver_H
#define FORCESPRONLPsolver_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif
#ifndef SOLVER_STRING_H
#define SOLVER_STRING_H
#include <string.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double FORCESPRONLPsolver_float;
typedef double FORCESPRONLPsolver_ldl_s_float;
typedef double FORCESPRONLPsolver_ldl_r_float;
typedef double FORCESPRONLPsolver_callback_float;

typedef double FORCESPRONLPsolverinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_FORCESPRONLPsolver
#define MISRA_C_FORCESPRONLPsolver (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_FORCESPRONLPsolver
#define RESTRICT_CODE_FORCESPRONLPsolver (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_FORCESPRONLPsolver
#define SET_PRINTLEVEL_FORCESPRONLPsolver    (0)
#endif

/* timing */
#ifndef SET_TIMING_FORCESPRONLPsolver
#define SET_TIMING_FORCESPRONLPsolver    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_FORCESPRONLPsolver			(200)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_FORCESPRONLPsolver		(FORCESPRONLPsolver_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_FORCESPRONLPsolver	(200) 

/* whether callback return values should be checked */
#define EXTFUNC_RETURN_FORCESPRONLPsolver (0)

/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_FORCESPRONLPsolver      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_FORCESPRONLPsolver (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_FORCESPRONLPsolver   (2)

/* solver stopped externally */
#define EXIT_EXTERNAL_FORCESPRONLPsolver (3)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_FORCESPRONLPsolver  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_FORCESPRONLPsolver   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_FORCESPRONLPsolver  (-6)

/* invalid value (<= -100) returned by external function */
#define INVALIDFUNCEXIT_FORCESPRONLPsolver (-200)

/* bad value returned by external function */
#define BADFUNCEXIT_FORCESPRONLPsolver(status) (status > -100? status - 200 : INVALIDFUNCEXIT_FORCESPRONLPsolver)

/* no progress in method possible */
#define NOPROGRESS_FORCESPRONLPsolver   (-7)

/* regularization error */
#define REGULARIZATION_ERROR_FORCESPRONLPsolver   (-9)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_FORCESPRONLPsolver   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_FORCESPRONLPsolver   (-12)

/* thread error */
#define THREAD_FAILURE_FORCESPRONLPsolver  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_FORCESPRONLPsolver  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_FORCESPRONLPsolver  (-100)

/* Insufficient number of internal memory instances.
 * Increase codeoptions.max_num_mem. */
#define MEMORY_INVALID_FORCESPRONLPsolver (-101)
/* Number of threads larger than specified.
 * Increase codeoptions.nlp.max_num_threads. */
#define NUMTHREADS_INVALID_FORCESPRONLPsolver (-102)


/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)


/* MEMORY STRUCT --------------------------------------------------------*/
typedef struct FORCESPRONLPsolver_mem FORCESPRONLPsolver_mem;
#ifdef __cplusplus
extern "C" {
#endif
/* MEMORY STRUCT --------------------------------------------------------*/
extern FORCESPRONLPsolver_mem * FORCESPRONLPsolver_external_mem(void * mem_ptr, solver_int32_unsigned i_mem, size_t mem_size);
extern size_t FORCESPRONLPsolver_get_mem_size( void );
extern size_t FORCESPRONLPsolver_get_const_size( void );
#ifdef __cplusplus
}
#endif

/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 9 */
    FORCESPRONLPsolver_float x0[9];

    /* vector of size 2 */
    FORCESPRONLPsolver_float xinit[2];

    /* vector of size 9 */
    FORCESPRONLPsolver_float all_parameters[9];


} FORCESPRONLPsolver_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* scalar */
    FORCESPRONLPsolver_float u0;


} FORCESPRONLPsolver_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* scalar: iteration number */
    solver_int32_default it;

    /* scalar: number of iterations needed to optimality (branch-and-bound) */
    solver_int32_default it2opt;

    /* scalar: inf-norm of equality constraint residuals */
    FORCESPRONLPsolver_float res_eq;

    /* scalar: inf-norm of inequality constraint residuals */
    FORCESPRONLPsolver_float res_ineq;

    /* scalar: norm of stationarity condition */
    FORCESPRONLPsolver_float rsnorm;

    /* scalar: max of all complementarity violations */
    FORCESPRONLPsolver_float rcompnorm;

    /* scalar: primal objective */
    FORCESPRONLPsolver_float pobj;

    /* scalar: dual objective */
    FORCESPRONLPsolver_float dobj;

    /* scalar: duality gap := pobj - dobj */
    FORCESPRONLPsolver_float dgap;

    /* scalar: relative duality gap := |dgap / pobj | */
    FORCESPRONLPsolver_float rdgap;

    /* scalar: duality measure */
    FORCESPRONLPsolver_float mu;

    /* scalar: duality measure (after affine step) */
    FORCESPRONLPsolver_float mu_aff;

    /* scalar: centering parameter */
    FORCESPRONLPsolver_float sigma;

    /* scalar: number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;

    /* scalar: number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;

    /* scalar: step size (affine direction) */
    FORCESPRONLPsolver_float step_aff;

    /* scalar: step size (combined direction) */
    FORCESPRONLPsolver_float step_cc;

    /* scalar: total solve time */
    FORCESPRONLPsolver_float solvetime;

    /* scalar: time spent in function evaluations */
    FORCESPRONLPsolver_float fevalstime;

    /* column vector of length 8: solver ID of FORCESPRO solver */
    solver_int32_default solver_id[8];




} FORCESPRONLPsolver_info;







/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Saturday, May 4, 2024 8:12:11 AM */
/* User License expires on: (UTC) Friday, September 6, 2024 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Friday, September 6, 2024 10:00:00 PM (approx.) */
/* Solver Id: ec07f515-b6ee-463f-b9da-4b55429d1f86 */
/* Host Compiler Version: d76500f0 */
/* Target Compiler Version: unused */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef solver_int32_default (*FORCESPRONLPsolver_extfunc)(FORCESPRONLPsolver_float* x, FORCESPRONLPsolver_float* y, FORCESPRONLPsolver_float* lambda, FORCESPRONLPsolver_float* params, FORCESPRONLPsolver_float* pobj, FORCESPRONLPsolver_float* g, FORCESPRONLPsolver_float* c, FORCESPRONLPsolver_float* Jeq, FORCESPRONLPsolver_float* h, FORCESPRONLPsolver_float* Jineq, FORCESPRONLPsolver_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default FORCESPRONLPsolver_solve(FORCESPRONLPsolver_params *params, FORCESPRONLPsolver_output *output, FORCESPRONLPsolver_info *info, FORCESPRONLPsolver_mem *mem, FILE *fs, FORCESPRONLPsolver_extfunc evalextfunctions_FORCESPRONLPsolver);











#ifdef __cplusplus
}
#endif

#endif
