
#ifndef FORCESPRONLPSOLVER_CASADI_H
#define FORCESPRONLPSOLVER_CASADI_H

/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int FORCESPRONLPsolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* FORCESPRONLPsolver_objective_1_sparsity_out(casadi_int i);
int FORCESPRONLPsolver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCESPRONLPsolver_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* FORCESPRONLPsolver_dynamics_1_sparsity_out(casadi_int i);
int FORCESPRONLPsolver_dynamics_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCESPRONLPsolver_objective_3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* FORCESPRONLPsolver_objective_3_sparsity_out(casadi_int i);
int FORCESPRONLPsolver_objective_3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
