/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCESPRONLPsolver_casadi_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s5[8] = {1, 3, 0, 0, 1, 2, 0, 0};

/* FORCESPRONLPsolver_objective_1:(i0[3],i1[3])->(o0,o1[1x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=100000.;
    a1=arg[1]? arg[1][0] : 0;
    a2=arg[0]? arg[0][1] : 0;
    a3=(a1-a2);
    a3=(a0*a3);
    a1=(a1-a2);
    a2=(a3*a1);
    a4=10000000.;
    a5=arg[1]? arg[1][1] : 0;
    a6=arg[0]? arg[0][2] : 0;
    a7=(a5-a6);
    a7=(a4*a7);
    a5=(a5-a6);
    a6=(a7*a5);
    a2=(a2+a6);
    a6=1.0000000000000000e-002;
    a8=arg[0]? arg[0][0] : 0;
    a9=(a6*a8);
    a10=(a9*a8);
    a2=(a2+a10);
    if (res[0]!=0) res[0][0]=a2;
    a6=(a6*a8);
    a9=(a9+a6);
    if (res[1]!=0) res[1][0]=a9;
    a0=(a0*a1);
    a3=(a3+a0);
    a3=(-a3);
    if (res[1]!=0) res[1][1]=a3;
    a4=(a4*a5);
    a7=(a7+a4);
    a7=(-a7);
    if (res[1]!=0) res[1][2]=a7;
    return 0;
}

int FORCESPRONLPsolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

const casadi_int* FORCESPRONLPsolver_objective_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        case 1: return casadi_s2;
        default: return 0;
    }
}

int FORCESPRONLPsolver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* FORCESPRONLPsolver_dynamics_1:(i0[3],i1[3])->(o0[2],o1[2x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[0]? arg[0][1] : 0;
    a1=1.6666666666666666e-004;
    a2=-1.5333333333333334e+000;
    a3=(a2*a0);
    a4=-9.9644444444444447e-001;
    a5=arg[0]? arg[0][2] : 0;
    a6=(a4*a5);
    a3=(a3+a6);
    a6=8.0000000000000004e-001;
    a7=arg[1]? arg[1][2] : 0;
    a8=(a6*a7);
    a3=(a3+a8);
    a8=2.;
    a9=5.0000000000000001e-004;
    a10=(a9*a3);
    a10=(a0+a10);
    a11=(a2*a10);
    a12=4.0000000000000002e-001;
    a13=(a12*a0);
    a14=-1.7226666666666666e+000;
    a15=(a14*a5);
    a13=(a13+a15);
    a15=2.5000000000000001e-004;
    a16=arg[0]? arg[0][0] : 0;
    a17=(a15*a16);
    a13=(a13+a17);
    a17=8.4000000000000004e+000;
    a18=(a17*a7);
    a13=(a13+a18);
    a18=(a9*a13);
    a18=(a5+a18);
    a19=(a4*a18);
    a11=(a11+a19);
    a19=(a6*a7);
    a11=(a11+a19);
    a19=(a8*a11);
    a3=(a3+a19);
    a11=(a9*a11);
    a11=(a0+a11);
    a19=(a2*a11);
    a10=(a12*a10);
    a18=(a14*a18);
    a10=(a10+a18);
    a18=(a15*a16);
    a10=(a10+a18);
    a18=(a17*a7);
    a10=(a10+a18);
    a9=(a9*a10);
    a9=(a5+a9);
    a18=(a4*a9);
    a19=(a19+a18);
    a18=(a6*a7);
    a19=(a19+a18);
    a18=(a8*a19);
    a3=(a3+a18);
    a18=1.0000000000000000e-003;
    a19=(a18*a19);
    a19=(a0+a19);
    a2=(a2*a19);
    a11=(a12*a11);
    a9=(a14*a9);
    a11=(a11+a9);
    a9=(a15*a16);
    a11=(a11+a9);
    a9=(a17*a7);
    a11=(a11+a9);
    a18=(a18*a11);
    a18=(a5+a18);
    a4=(a4*a18);
    a2=(a2+a4);
    a6=(a6*a7);
    a2=(a2+a6);
    a3=(a3+a2);
    a3=(a1*a3);
    a0=(a0+a3);
    if (res[0]!=0) res[0][0]=a0;
    a10=(a8*a10);
    a13=(a13+a10);
    a8=(a8*a11);
    a13=(a13+a8);
    a12=(a12*a19);
    a14=(a14*a18);
    a12=(a12+a14);
    a15=(a15*a16);
    a12=(a12+a15);
    a17=(a17*a7);
    a12=(a12+a17);
    a13=(a13+a12);
    a1=(a1*a13);
    a5=(a5+a1);
    if (res[0]!=0) res[0][1]=a5;
    a5=-1.2442044974520238e-010;
    if (res[1]!=0) res[1][0]=a5;
    a5=2.4978477367586353e-007;
    if (res[1]!=0) res[1][1]=a5;
    a5=9.9846764265063026e-001;
    if (res[1]!=0) res[1][2]=a5;
    a5=3.9934930385703135e-004;
    if (res[1]!=0) res[1][3]=a5;
    a5=-9.9482348805273791e-004;
    if (res[1]!=0) res[1][4]=a5;
    a5=9.9827861731347123e-001;
    if (res[1]!=0) res[1][5]=a5;
    return 0;
}

int FORCESPRONLPsolver_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f1(arg, res, iw, w, mem);
}

const casadi_int* FORCESPRONLPsolver_dynamics_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        case 1: return casadi_s4;
        default: return 0;
    }
}

int FORCESPRONLPsolver_dynamics_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* FORCESPRONLPsolver_objective_3:(i0[3],i1[3])->(o0,o1[1x3,2nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
    a0=3.3828164768102765e+007;
    a1=arg[1]? arg[1][0] : 0;
    a2=arg[0]? arg[0][1] : 0;
    a3=(a1-a2);
    a0=(a0*a3);
    a4=2.2217494650890149e+007;
    a5=arg[1]? arg[1][1] : 0;
    a6=arg[0]? arg[0][2] : 0;
    a7=(a5-a6);
    a8=(a4*a7);
    a0=(a0+a8);
    a1=(a1-a2);
    a2=(a0*a1);
    a4=(a4*a3);
    a3=2.5257466444342293e+007;
    a3=(a3*a7);
    a4=(a4+a3);
    a5=(a5-a6);
    a6=(a4*a5);
    a2=(a2+a6);
    if (res[0]!=0) res[0][0]=a2;
    a2=-3.3828164768102765e+007;
    a2=(a2*a1);
    a2=(a2-a0);
    a0=-2.2217494650890149e+007;
    a6=(a0*a5);
    a2=(a2+a6);
    if (res[1]!=0) res[1][0]=a2;
    a0=(a0*a1);
    a1=-2.5257466444342293e+007;
    a1=(a1*a5);
    a1=(a1-a4);
    a0=(a0+a1);
    if (res[1]!=0) res[1][1]=a0;
    return 0;
}

int FORCESPRONLPsolver_objective_3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f2(arg, res, iw, w, mem);
}

const casadi_int* FORCESPRONLPsolver_objective_3_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        case 1: return casadi_s5;
        default: return 0;
    }
}

int FORCESPRONLPsolver_objective_3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
